### PR TITLE
Big Endian support and flexible adoptions by end-users

### PR DESCRIPTION
**Pull request by utillity**
added some big-endian packers and unpackers. also made packers and unpackers available in export for override/extension by end-users

### CODE REVIEW

**Comment by xiatian** [comment]
nice

**Comment by majimboo** [comment]
Thank you for the PR. I haven't really got around into updating this project as I've moved on to Golang.

**Comment by utillity** [comment]
you're welcome!

**Comment by utillity** [comment]
are you going to publish an NPM package as well?

**Comment by majimboo** [comment]
@utillity yes, give me a few. :)

**Comment by majimboo** [comment]
@utillity NPM package updated to 0.0.5

**Pull request merged**
